#server-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - port: 5050
      targetPort: 5050
  type: ClusterIP  # Internal service only
